import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const backendFiles = [
  "generated/date-simulator-v1.5.5.js",
  "compiler.js",
  "scorers.js",
  "benchmarks.js",
  "runner.js",
  "backend.js",
];
const packageJson = JSON.parse(await readFile(join(projectRoot, "package.json"), "utf8"));

function stripModuleSyntax(source) {
  return source
    .replace(/^import\s*\{[\s\S]*?\}\s*from\s*["'][^"']+["'];\s*/gm, "")
    .replace(/^export[ \t]+/gm, "");
}

const backendParts = [];
for (const file of backendFiles) {
  backendParts.push(stripModuleSyntax(await readFile(join(projectRoot, "src", file), "utf8")));
}

await mkdir(join(projectRoot, "dist"), { recursive: true });
await writeFile(
  join(projectRoot, "dist", "backend.js"),
  `// Generated by scripts/build.mjs. Do not edit directly.\n// Date Simulator Model Evaluator v${packageJson.version}\n\n${backendParts.join("\n\n")}`,
  "utf8",
);
await writeFile(
  join(projectRoot, "dist", "frontend.js"),
  `// Generated by scripts/build.mjs. Do not edit directly.\n${await readFile(join(projectRoot, "src", "frontend.js"), "utf8")}`,
  "utf8",
);

console.log("Built dist/backend.js and dist/frontend.js");
